# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.expense_response import ExpenseResponse
from openapi_server import util

from openapi_server.models.expense_response import ExpenseResponse  # noqa: E501

class ExpensesResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, expenses=None):  # noqa: E501
        """ExpensesResponse - a model defined in OpenAPI

        :param expenses: The expenses of this ExpensesResponse.  # noqa: E501
        :type expenses: List[ExpenseResponse]
        """
        self.openapi_types = {
            'expenses': List[ExpenseResponse]
        }

        self.attribute_map = {
            'expenses': 'expenses'
        }

        self._expenses = expenses

    @classmethod
    def from_dict(cls, dikt) -> 'ExpensesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpensesResponse of this ExpensesResponse.  # noqa: E501
        :rtype: ExpensesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def expenses(self):
        """Gets the expenses of this ExpensesResponse.

        支出一覧リスト  # noqa: E501

        :return: The expenses of this ExpensesResponse.
        :rtype: List[ExpenseResponse]
        """
        return self._expenses

    @expenses.setter
    def expenses(self, expenses):
        """Sets the expenses of this ExpensesResponse.

        支出一覧リスト  # noqa: E501

        :param expenses: The expenses of this ExpensesResponse.
        :type expenses: List[ExpenseResponse]
        """

        self._expenses = expenses
