# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NotFound(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None):  # noqa: E501
        """NotFound - a model defined in OpenAPI

        :param code: The code of this NotFound.  # noqa: E501
        :type code: str
        :param message: The message of this NotFound.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'code': str,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'NotFound':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotFound of this NotFound.  # noqa: E501
        :rtype: NotFound
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this NotFound.

        エラーコード  # noqa: E501

        :return: The code of this NotFound.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this NotFound.

        エラーコード  # noqa: E501

        :param code: The code of this NotFound.
        :type code: str
        """

        self._code = code

    @property
    def message(self):
        """Gets the message of this NotFound.

        エラーメッセージ  # noqa: E501

        :return: The message of this NotFound.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this NotFound.

        エラーメッセージ  # noqa: E501

        :param message: The message of this NotFound.
        :type message: str
        """

        self._message = message
